apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "replicalimit-binding-test.example.com"
spec:
  policyName: "replicalimit-policy.example.com"
  paramRef:
    name: "replica-limit-test.example.com"
  matchResources:
    resourceRules:
      - apiGroups:   ["apps"]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["deployments"]
    objectSelector:
      matchExpressions:
        - key: app
          operator: In
          values: ["nginx"]
#    namespaceSelector:
#      matchExpressions:
#        - key: environment
#          operator: In
#          values: ["test"]
