apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: 'my-registry.io/images/example@sha256:aaaabbbbccccddddeeeeffffgggghhhh'
    ports:
    - containerPort: 80
