apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "replicalimit-policy.example.com"
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:   ["apps"]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= 100"
    - expression: "object.spec.replicas <= 3"
    - expression: "x > y"
    - expression: "object.spec.replicas <= 2"
    - expression: "!!!"
    - expression: "object.x < object.y"

