apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "replicalimit-binding-test.example.com"
spec:
  policyName: "replicalimit-policy.example.com"
#  matchResources:
#    namespaceSelector:
#      matchExpressions:
#        - key: environment
#          operator: In
#          values: ["test"]
